use_frameworks!

platform :ios, '9.0'

target 'DeviceData_Example' do
  pod 'DeviceData', :path => '../'
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireObjectMapper'

  target 'DeviceData_Tests' do
    inherit! :search_paths

    
  end
end
